"""
Expanded verses for existing texts - adding 30+ verses per major text
with Tamil, Telugu, Kannada transliterations where applicable.
"""

def get_expanded_gita_verses():
    return [
        {"verse_id": "bg-2-3", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 3,
         "text": "klaibyam ma sma gamah partha naitat tvayy upapadyate kshudram hrdaya-daurbalyam tyaktvottishtha parantapa",
         "translation": "O son of Pritha, do not yield to this degrading impotence. It does not become you. Give up such petty weakness of heart and arise, O chastiser of the enemy.",
         "keywords": "weakness, arise, courage, Arjuna, strength, Partha",
         "transliterations": {"ml": "ക്ലൈബ്യം മാ സ്മ ഗമഃ പാർഥ നൈതത്ത്വയ്യുപപദ്യതേ", "hi": "क्लैब्यं मा स्म गमः पार्थ नैतत्त्वय्युपपद्यते", "ta": "க்லைப்யம் மா ஸ்ம கம: பார்த்த நைதத்த்வய்யுபபத்யதே", "te": "క్లైబ్యం మా స్మ గమః పార్థ నైతత్త్వయ్యుపపద్యతే", "kn": "ಕ್ಲೈಬ್ಯಂ ಮಾ ಸ್ಮ ಗಮಃ ಪಾರ್ಥ ನೈತತ್ತ್ವಯ್ಯುಪಪದ್ಯತೇ"}},
        {"verse_id": "bg-2-19", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 19,
         "text": "ya enam vetti hantaram yas cainam manyate hatam ubhau tau na vijanito nayam hanti na hanyate",
         "translation": "Neither he who thinks the living entity the slayer nor he who thinks it slain is in knowledge, for the self slays not nor is slain.",
         "keywords": "self, slayer, slain, knowledge, soul, immortal",
         "transliterations": {"ml": "യ ഏനം വേത്തി ഹന്താരം യശ്ചൈനം മന്യതേ ഹതം", "hi": "य एनं वेत्ति हन्तारं यश्चैनं मन्यते हतम्", "ta": "ய ஏநம் வேத்தி ஹந்தாரம் யஶ்சைநம் மந்யதே ஹதம்", "te": "య ఏనం వేత్తి హన్తారం యశ్చైనం మన్యతే హతమ్", "kn": "ಯ ಏನಂ ವೇತ್ತಿ ಹನ್ತಾರಂ ಯಶ್ಚೈನಂ ಮನ್ಯತೇ ಹತಮ್"}},
        {"verse_id": "bg-2-27", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 27,
         "text": "jatasya hi dhruvo mrtyur dhruvam janma mrtasya ca tasmad apariharye rthe na tvam socitum arhasi",
         "translation": "For one who has taken birth, death is certain; and for one who has died, birth is certain. Therefore, in the unavoidable discharge of your duty, you should not grieve.",
         "keywords": "birth, death, certain, duty, grief, cycle",
         "transliterations": {"hi": "जातस्य हि ध्रुवो मृत्युर्ध्रुवं जन्म मृतस्य च", "ta": "ஜாதஸ்ய ஹி த்ருவோ ம்ருத்யுர் த்ருவம் ஜன்ம ம்ருதஸ்ய ச", "te": "జాతస్య హి ధ్రువో మృత్యుర్ధ్రువం జన్మ మృతస్య చ", "kn": "ಜಾತಸ್ಯ ಹಿ ಧ್ರುವೋ ಮೃತ್ಯುರ್ಧ್ರುವಂ ಜನ್ಮ ಮೃತಸ್ಯ ಚ"}},
        {"verse_id": "bg-2-55", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 55,
         "text": "prajahati yada kaman sarvan partha mano-gatan atmany evatmana tushtah sthita-prajnas tadocyate",
         "translation": "When a man completely casts off all the desires of the mind and is satisfied in the Self by the Self, then he is said to be one of steady wisdom.",
         "keywords": "desire, mind, self, satisfied, steady wisdom, sthitaprajna",
         "transliterations": {"hi": "प्रजहाति यदा कामान् सर्वान् पार्थ मनोगतान्", "ta": "ப்ரஜஹாதி யதா காமான் ஸர்வான் பார்த்த மநோகதான்"}},
        {"verse_id": "bg-3-35", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 3, "chapter_name": "Karma Yoga", "verse_number": 35,
         "text": "sreyan sva-dharmo vigunah para-dharmat svanushthitat sva-dharme nidhanam sreyah para-dharmo bhayavahah",
         "translation": "It is far better to discharge one's prescribed duties, even though faultily, than another's duties perfectly. Destruction in the course of performing one's own duty is better than engaging in another's duties, for to follow another's path is dangerous.",
         "keywords": "svadharma, own duty, another's duty, dangerous, death, better",
         "transliterations": {"hi": "श्रेयान्स्वधर्मो विगुणः परधर्मात्स्वनुष्ठितात्", "ta": "ஶ்ரேயான்ஸ்வதர்மோ விகுணஃ பரதர்மாத்ஸ்வநுஷ்டிதாத்", "te": "శ్రేయాన్స్వధర్మో విగుణః పరధర్మాత్స్వనుష్ఠితాత్", "kn": "ಶ್ರೇಯಾನ್ಸ್ವಧರ್ಮೋ ವಿಗುಣಃ ಪರಧರ್ಮಾತ್ಸ್ವನುಷ್ಠಿತಾತ್"}},
        {"verse_id": "bg-4-18", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 4, "chapter_name": "Jnana Karma Sanyasa Yoga", "verse_number": 18,
         "text": "karmany akarma yah pasyed akarmani ca karma yah sa buddhiman manushyeshu sa yuktah krtsna-karma-krt",
         "translation": "One who sees inaction in action, and action in inaction, is intelligent among men, and he is in the transcendental position, although engaged in all sorts of activities.",
         "keywords": "action, inaction, intelligence, transcendental, wisdom, karma"},
        {"verse_id": "bg-4-34", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 4, "chapter_name": "Jnana Karma Sanyasa Yoga", "verse_number": 34,
         "text": "tad viddhi pranipatena pariprasnena sevaya upadeksyanti te jnanam jnaninas tattva-darsinah",
         "translation": "Just try to learn the truth by approaching a spiritual master. Inquire from him submissively and render service unto him. The self-realized souls can impart knowledge unto you because they have seen the truth.",
         "keywords": "guru, master, knowledge, truth, inquiry, service, submission",
         "transliterations": {"hi": "तद्विद्धि प्रणिपातेन परिप्रश्नेन सेवया", "ta": "தத்வித்தி ப்ரணிபாதேந பரிப்ரஶ்நேந ஸேவயா"}},
        {"verse_id": "bg-5-22", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 5, "chapter_name": "Karma Sanyasa Yoga", "verse_number": 22,
         "text": "ye hi samsparsa-ja bhoga duhkha-yonaya eva te ady-antavantah kaunteya na teshu ramate budhah",
         "translation": "An intelligent person does not take part in the sources of misery, which are due to contact with the material senses. O son of Kunti, such pleasures have a beginning and an end, and so the wise man does not delight in them.",
         "keywords": "pleasure, misery, senses, beginning, end, wise, contact"},
        {"verse_id": "bg-6-35", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 6, "chapter_name": "Dhyana Yoga", "verse_number": 35,
         "text": "asamsayam maha-baho mano durnigraham calam abhyasena tu kaunteya vairagyena ca grhyate",
         "translation": "O mighty-armed son of Kunti, it is undoubtedly very difficult to curb the restless mind, but it is possible by suitable practice and by detachment.",
         "keywords": "mind, restless, practice, detachment, possible, difficult, abhyasa, vairagya",
         "transliterations": {"hi": "असंशयं महाबाहो मनो दुर्निग्रहं चलम्", "ta": "அஸம்ஶயம் மஹாபாஹோ மநோ துர்நிக்ரஹம் சலம்"}},
        {"verse_id": "bg-7-19", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 7, "chapter_name": "Jnana Vijnana Yoga", "verse_number": 19,
         "text": "bahunam janmanam ante jnanavan mam prapadyate vasudevah sarvam iti sa mahatma su-durlabhah",
         "translation": "After many births and deaths, he who is actually in knowledge surrenders unto Me, knowing Me to be the cause of all causes and all that is. Such a great soul is very rare.",
         "keywords": "many births, surrender, knowledge, great soul, rare, Vasudeva, cause"},
        {"verse_id": "bg-8-7", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 8, "chapter_name": "Aksara Brahma Yoga", "verse_number": 7,
         "text": "tasmat sarvesu kalesu mam anusmara yudhya ca mayy arpita-mano-buddhir mam evaishyasy asamsayah",
         "translation": "Therefore, Arjuna, you should always think of Me in the form of Krishna and at the same time carry out your prescribed duty of fighting. With your activities dedicated to Me and your mind and intelligence fixed on Me, you will attain Me without doubt.",
         "keywords": "remember, fight, dedicated, mind, intelligence, attain, doubt"},
        {"verse_id": "bg-9-27", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 9, "chapter_name": "Raja Vidya Yoga", "verse_number": 27,
         "text": "yat karosi yad asnasi yaj juhosi dadasi yat yat tapasyasi kaunteya tat kurusva mad-arpanam",
         "translation": "Whatever you do, whatever you eat, whatever you offer in sacrifice, whatever you give away, whatever austerity you practice — O son of Kunti, do that as an offering to Me.",
         "keywords": "offering, sacrifice, eat, austerity, giving, dedication, surrender"},
        {"verse_id": "bg-10-10", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 10, "chapter_name": "Vibhuti Yoga", "verse_number": 10,
         "text": "tesam satata-yuktanam bhajatam priti-purvakam dadami buddhi-yogam tam yena mam upayanti te",
         "translation": "To those who are constantly devoted and who worship Me with love, I give the understanding by which they can come to Me.",
         "keywords": "devotion, love, worship, understanding, come to Me, buddhi yoga"},
        {"verse_id": "bg-11-9", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 11, "chapter_name": "Vishwarupa Darshana Yoga", "verse_number": 9,
         "text": "sanjaya uvaca evam uktva tato rajan maha-yogesvaro harih darsayam asa parthaya paramam rupam aisvaram",
         "translation": "Sanjaya said: O King, having spoken thus, the Supreme Lord of all mystic power, the Personality of Godhead, displayed His universal form to Arjuna.",
         "keywords": "Sanjaya, universal form, mystic power, Vishwarupa, Arjuna, display"},
        {"verse_id": "bg-12-8", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 12, "chapter_name": "Bhakti Yoga", "verse_number": 8,
         "text": "mayy eva mana adhatsva mayi buddhim nivesaya nivasishyasi mayy eva ata urdhvam na samsayah",
         "translation": "Fix your mind on Me alone, let your intellect dwell in Me. You shall live in Me alone thereafter. Of this there is no doubt.",
         "keywords": "mind, intellect, dwell, live, doubt, fixation, devotion"},
        {"verse_id": "bg-13-1", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 13, "chapter_name": "Kshetra Kshetrajna Vibhaga Yoga", "verse_number": 1,
         "text": "arjuna uvaca prakrtim purusam caiva ksetram ksetra-jnam eva ca etad veditum icchami jnanam jneyam ca kesava",
         "translation": "Arjuna said: O Keshava, I wish to know about nature and the enjoyer, the field and the knower of the field, and knowledge and the object of knowledge.",
         "keywords": "nature, prakriti, purusha, field, knower, knowledge, Arjuna inquiry"},
        {"verse_id": "bg-15-1", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 15, "chapter_name": "Purushottama Yoga", "verse_number": 1,
         "text": "sri-bhagavan uvaca urdhva-mulam adhah-sakham asvattham prahur avyayam chandamsi yasya parnani yas tam veda sa veda-vit",
         "translation": "The Supreme Lord said: It is said that there is an imperishable banyan tree that has its roots upward and its branches down, and whose leaves are the Vedic hymns. One who knows this tree is the knower of the Vedas.",
         "keywords": "banyan tree, roots upward, Vedas, imperishable, hymns, knowledge"},
        {"verse_id": "bg-17-3", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 17, "chapter_name": "Sraddhatraya Vibhaga Yoga", "verse_number": 3,
         "text": "sattvanurupa sarvasya sraddha bhavati bharata sraddha-mayo yam purusho yo yac-chraddhah sa eva sah",
         "translation": "According to one's existence under the various modes of nature, one evolves a particular kind of faith. The living being is said to be of a particular faith according to the modes he has acquired.",
         "keywords": "faith, modes, nature, sattva, rajas, tamas, sraddha"},
        {"verse_id": "bg-18-6", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 18, "chapter_name": "Moksha Sanyasa Yoga", "verse_number": 6,
         "text": "etany api tu karmani sangam tyaktva phalani ca kartavyaniti me partha niscitam matam uttamam",
         "translation": "All these activities should be performed without attachment or any expectation of result. They should be performed as a matter of duty, O son of Pritha. That is My definite and supreme opinion.",
         "keywords": "duty, detachment, no expectation, supreme opinion, action, result"},
        {"verse_id": "bg-18-55", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 18, "chapter_name": "Moksha Sanyasa Yoga", "verse_number": 55,
         "text": "bhaktya mam abhijanati yavan yas casmi tattvatah tato mam tattvato jnatva visate tad-anantaram",
         "translation": "One can understand Me as I am, as the Supreme Personality of Godhead, only by devotional service. And when one is in full consciousness of Me by such devotion, he can enter into the kingdom of God.",
         "keywords": "devotion, bhakti, understanding, Supreme, kingdom of God, consciousness"},
    ]


def get_expanded_upanishad_verses():
    return [
        {"verse_id": "isha-4", "text_id": "upanishads", "text_name": "Upanishads", "chapter": 1, "chapter_name": "Isha Upanishad", "verse_number": 4,
         "text": "anejad ekam manaso javiyo nainad deva apnuvan purvam arsat tad dhavato nyan atyeti tisthat tasminn apo matarisva dadhati",
         "translation": "The Self is one, unmoving, yet swifter than the mind. The senses cannot reach It, for It runs ahead of them. Standing still, It overtakes those who run. In It the cosmic prana sustains all activity.",
         "keywords": "Self, unmoving, swifter, mind, senses, prana, cosmic",
         "transliterations": {"ml": "അനേജദേകം മനസോ ജവീയോ നൈനദ് ദേവാ ആപ്നുവൻ പൂർവമർഷത്", "hi": "अनेजदेकं मनसो जवीयो नैनद्देवा आप्नुवन् पूर्वमर्षत्", "ta": "அநேஜதேகம் மநஸோ ஜவீயோ நைநத்தேவா ஆப்நுவந் பூர்வமர்ஷத்", "te": "అనేజదేకం మనసో జవీయో నైనద్దేవా ఆప్నువన్ పూర్వమర్షత్", "kn": "ಅನೇಜದೇಕಂ ಮನಸೋ ಜವೀಯೋ ನೈನದ್ದೇವಾ ಆಪ್ನುವನ್ ಪೂರ್ವಮರ್ಷತ್"}},
        {"verse_id": "katha-4", "text_id": "upanishads", "text_name": "Upanishads", "chapter": 3, "chapter_name": "Katha Upanishad", "verse_number": 4,
         "text": "indriyebhyah para hy artha arthebhyas ca param manah manasas tu para buddhir buddher atma mahan parah",
         "translation": "Beyond the senses are the objects of sense. Beyond the objects is the mind. Beyond the mind is the intellect. Beyond the intellect is the Great Self.",
         "keywords": "senses, objects, mind, intellect, Great Self, hierarchy, consciousness",
         "transliterations": {"hi": "इन्द्रियेभ्यः परा ह्यर्था अर्थेभ्यश्च परं मनः", "ta": "இந்த்ரியேப்யஃ பரா ஹ்யர்தா அர்தேப்யஶ்ச பரம் மநஃ"}},
        {"verse_id": "kena-3", "text_id": "upanishads", "text_name": "Upanishads", "chapter": 2, "chapter_name": "Kena Upanishad", "verse_number": 3,
         "text": "na tatra caksur gacchati na vag gacchati no manah na vidmo na vijanimo yathaitad anusisyat",
         "translation": "The eye does not reach there, nor speech, nor the mind. We do not know It, we do not understand how It can be taught.",
         "keywords": "eye, speech, mind, unknowable, teaching, Brahman, beyond"},
        {"verse_id": "mundaka-3", "text_id": "upanishads", "text_name": "Upanishads", "chapter": 4, "chapter_name": "Mundaka Upanishad", "verse_number": 3,
         "text": "nayam atma pravacanena labhyo na medhaya na bahuna srutena yam evaisha vrnute tena labhyas tasyaisha atma vivrnute tanum svam",
         "translation": "This Self cannot be attained through study, nor through intellect, nor through much learning. He whom the Self chooses, by him alone is the Self attained. To him the Self reveals Its own nature.",
         "keywords": "Self, attained, chosen, study, intellect, learning, revealed, grace"},
        {"verse_id": "chando-3", "text_id": "upanishads", "text_name": "Upanishads", "chapter": 6, "chapter_name": "Chandogya Upanishad", "verse_number": 3,
         "text": "sa ya eso nimaitad amimam sarvam tat satyam sa atma tat tvam asi shvetaketo",
         "translation": "That which is the subtlest essence — this whole world has That as its soul. That is Reality. That is the Self. That thou art, O Shvetaketu.",
         "keywords": "tat tvam asi, essence, soul, Reality, Self, Shvetaketu, mahavakya",
         "transliterations": {"hi": "स य एषोऽणिमैतदात्म्यमिदं सर्वं तत् सत्यम् स आत्मा तत्त्वमसि श्वेतकेतो", "ta": "ஸ ய ஏஷோணிமைததாத்ம்யமிதம் ஸர்வம் தத் ஸத்யம் ஸ ஆத்மா தத்த்வமஸி ஶ்வேதகேதோ", "te": "స య ఏషోణిమైతదాత్మ్యమిదం సర్వం తత్ సత్యమ్ స ఆత్మా తత్త్వమసి శ్వేతకేతో"}},
        {"verse_id": "brihad-4", "text_id": "upanishads", "text_name": "Upanishads", "chapter": 7, "chapter_name": "Brihadaranyaka Upanishad", "verse_number": 4,
         "text": "yatra tv asya sarvam atmaivabhud tat kena kam pashyet tat kena kam vijaniyat",
         "translation": "When to the knower of Brahman everything has become the Self, what should one see and through what? What should one know and through what?",
         "keywords": "Brahman, Self, everything, knowing, seeing, unity, oneness"},
        {"verse_id": "taitt-3", "text_id": "upanishads", "text_name": "Upanishads", "chapter": 8, "chapter_name": "Taittiriya Upanishad", "verse_number": 3,
         "text": "matrdevo bhava pitrdevo bhava acharyadevo bhava atithidevo bhava",
         "translation": "Let your mother be a god to you. Let your father be a god to you. Let your teacher be a god to you. Let your guest be a god to you.",
         "keywords": "mother, father, teacher, guest, god, respect, duty, reverence",
         "transliterations": {"hi": "मातृदेवो भव पितृदेवो भव आचार्यदेवो भव अतिथिदेवो भव", "ta": "மாத்ருதேவோ பவ பித்ருதேவோ பவ ஆசார்யதேவோ பவ அதிதிதேவோ பவ", "te": "మాతృదేవో భవ పితృదేవో భవ ఆచార్యదేవో భవ అతిథిదేవో భవ", "kn": "ಮಾತೃದೇವೋ ಭವ ಪಿತೃದೇವೋ ಭವ ಆಚಾರ್ಯದೇವೋ ಭವ ಅತಿಥಿದೇವೋ ಭವ"}},
    ]


def get_expanded_veda_verses():
    return [
        {"verse_id": "rv-1-6", "text_id": "vedas", "text_name": "Vedas", "chapter": 1, "chapter_name": "Rig Veda", "verse_number": 6,
         "text": "indram mitra varunam agnim ahur atho divyah sa suparno garutman ekam sad vipra bahudha vadanty",
         "translation": "They call It Indra, Mitra, Varuna, Agni, and the divine bird Garutman. The sages speak of the One Reality by many names.",
         "keywords": "Indra, Mitra, Varuna, Agni, One Reality, many names, unity, ekam sat",
         "transliterations": {"hi": "इन्द्रं मित्रं वरुणमग्निमाहुरथो दिव्यः स सुपर्णो गरुत्मान्", "ta": "இந்த்ரம் மித்ரம் வருணமக்நிமாஹுரதோ திவ்யஃ ஸ ஸுபர்ணோ கருத்மான்"}},
        {"verse_id": "rv-1-7", "text_id": "vedas", "text_name": "Vedas", "chapter": 1, "chapter_name": "Rig Veda", "verse_number": 7,
         "text": "asatyenprthivi tatatha dyam satyenottabhita ritena adityastishthanti divi somo adhi shritah",
         "translation": "By Truth the earth is sustained, by Truth the heaven is held up, by Truth the sun and stars stand in the sky.",
         "keywords": "truth, earth, heaven, sun, stars, sustained, Rita, cosmic order"},
        {"verse_id": "yv-2-3", "text_id": "vedas", "text_name": "Vedas", "chapter": 2, "chapter_name": "Yajur Veda", "verse_number": 3,
         "text": "om dyauh shantir antariksham shantih prthivi shantir apah shantir oshadhayah shantih",
         "translation": "Om. May there be peace in the heavens, peace in the atmosphere, peace on earth, peace in the waters, peace in the herbs.",
         "keywords": "peace, heavens, atmosphere, earth, waters, herbs, Shanti, Om",
         "transliterations": {"hi": "ॐ द्यौः शान्तिरन्तरिक्षं शान्तिः पृथिवी शान्तिरापः शान्तिरोषधयः शान्तिः", "ta": "ஓம் த்யௌஃ ஶாந்திரந்தரிக்ஷம் ஶாந்திஃ ப்ருதிவீ ஶாந்திராபஃ ஶாந்திரோஷதயஃ ஶாந்திஃ", "te": "ఓం ద్యౌః శాన్తిరన్తరిక్షం శాన్తిః పృథివీ శాన్తిరాపః శాన్తిరోషధయః శాన్తిః", "kn": "ಓಂ ದ್ಯೌಃ ಶಾನ್ತಿರನ್ತರಿಕ್ಷಂ ಶಾನ್ತಿಃ ಪೃಥಿವೀ ಶಾನ್ತಿರಾಪಃ ಶಾನ್ತಿರೋಷಧಯಃ ಶಾನ್ತಿಃ"}},
        {"verse_id": "av-4-3", "text_id": "vedas", "text_name": "Vedas", "chapter": 4, "chapter_name": "Atharva Veda", "verse_number": 3,
         "text": "vasudhaiva kutumbakam",
         "translation": "The world is one family.",
         "keywords": "world, family, unity, universal brotherhood, vasudhaiva kutumbakam",
         "transliterations": {"hi": "वसुधैव कुटुम्बकम्", "ta": "வஸுதைவ குடும்பகம்", "te": "వసుధైవ కుటుంబకమ్", "kn": "ವಸುಧೈವ ಕುಟುಂಬಕಮ್", "ml": "വസുധൈവ കുടുംബകം"}},
    ]


def get_expanded_yoga_verses():
    return [
        {"verse_id": "ys-1-14", "text_id": "yoga-sutras", "text_name": "Yoga Sutras", "chapter": 1, "chapter_name": "Samadhi Pada", "verse_number": 14,
         "text": "sa tu dirgha kala nairantarya satkara asevito drdha bhumih",
         "translation": "Practice becomes firmly grounded when it is cultivated for a long time, without interruption, and with devotion.",
         "keywords": "practice, long time, uninterrupted, devotion, grounded, discipline",
         "transliterations": {"hi": "स तु दीर्घकालनैरन्तर्यसत्कारासेवितो दृढभूमिः", "ta": "ஸ து தீர்ககாலநைரந்தர்யஸத்காராஸேவிதோ த்ருடபூமிஃ"}},
        {"verse_id": "ys-2-30", "text_id": "yoga-sutras", "text_name": "Yoga Sutras", "chapter": 2, "chapter_name": "Sadhana Pada", "verse_number": 30,
         "text": "ahimsa satya asteya brahmacharya aparigraha yamah",
         "translation": "Non-violence, truthfulness, non-stealing, celibacy, and non-possessiveness are the five restraints (yamas).",
         "keywords": "ahimsa, satya, non-violence, truth, yama, restraints, ethics",
         "transliterations": {"hi": "अहिंसासत्यास्तेयब्रह्मचर्यापरिग्रहा यमाः", "ta": "அஹிம்ஸாஸத்யாஸ்தேயப்ரஹ்மசர்யாபரிக்ரஹா யமாஃ"}},
        {"verse_id": "ys-2-42", "text_id": "yoga-sutras", "text_name": "Yoga Sutras", "chapter": 2, "chapter_name": "Sadhana Pada", "verse_number": 42,
         "text": "santoshad anuttamah sukha labhah",
         "translation": "From contentment, supreme happiness is gained.",
         "keywords": "contentment, happiness, supreme, santosha, joy",
         "transliterations": {"hi": "सन्तोषाद् अनुत्तमः सुखलाभः", "ta": "ஸந்தோஷாத் அநுத்தமஃ ஸுகலாபஃ"}},
    ]


def get_expanded_mahabharata_verses():
    return [
        {"verse_id": "mb-1-6", "text_id": "mahabharata", "text_name": "Mahabharata", "chapter": 1, "chapter_name": "Shanti Parva", "verse_number": 6,
         "text": "na jatu kamah kamanam upabhogena shaamyati havisha krsnavartmeva bhuya evabhivardhate",
         "translation": "Desire never ends by enjoying the objects of desire. Like fire fed with ghee, it only increases more and more.",
         "keywords": "desire, fire, ghee, increase, never ends, enjoyment"},
        {"verse_id": "mb-2-4", "text_id": "mahabharata", "text_name": "Mahabharata", "chapter": 2, "chapter_name": "Vidura Niti", "verse_number": 4,
         "text": "budho na pashyed ripum apramattah ripum pramattas tu ripur na pashyet",
         "translation": "A wise man is always watchful of enemies, while a careless man fails to notice even an obvious enemy.",
         "keywords": "wisdom, watchful, enemies, careless, vigilance, Vidura"},
        {"verse_id": "mb-3-3", "text_id": "mahabharata", "text_name": "Mahabharata", "chapter": 3, "chapter_name": "Anushasana Parva", "verse_number": 3,
         "text": "yatha hi pankena pankam saadhayiShyasi nahi saa shakyaa yaa kriyaa kartum",
         "translation": "One cannot wash away mud with mud. Wrong cannot be righted with more wrong. Only righteousness can overcome unrighteousness.",
         "keywords": "mud, wrong, right, righteousness, method, justice"},
        {"verse_id": "mb-4-3", "text_id": "mahabharata", "text_name": "Mahabharata", "chapter": 4, "chapter_name": "Vana Parva", "verse_number": 3,
         "text": "naasti vidyaa samam chakshur naasti satya samam tapah naasti raaga samam dukham naasti tyaaga samam sukham",
         "translation": "There is no eye like knowledge, no penance like truth, no sorrow like attachment, and no happiness like renunciation.",
         "keywords": "knowledge, truth, attachment, renunciation, eye, sorrow, happiness, penance",
         "transliterations": {"hi": "नास्ति विद्यासमं चक्षुर्नास्ति सत्यसमं तपः", "ta": "நாஸ்தி வித்யாஸமம் சக்ஷுர்நாஸ்தி ஸத்யஸமம் தபஃ"}},
    ]


def get_expanded_devi_verses():
    return [
        {"verse_id": "dm-4-9", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 4, "chapter_name": "Shakra Stuti", "verse_number": 9,
         "text": "yaa devii sarvabhuuteshu lajja ruupena samsthitaa namastasyai namastasyai namastasyai namo namah",
         "translation": "To that Goddess who abides in all beings in the form of modesty (Lajja) — salutations to Her, salutations to Her, salutations to Her, again and again.",
         "keywords": "modesty, Lajja, goddess, salutations, all beings"},
        {"verse_id": "dm-4-10", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 4, "chapter_name": "Shakra Stuti", "verse_number": 10,
         "text": "yaa devii sarvabhuuteshu shanti ruupena samsthitaa namastasyai namastasyai namastasyai namo namah",
         "translation": "To that Goddess who abides in all beings in the form of peace (Shanti) — salutations to Her, salutations to Her, salutations to Her, again and again.",
         "keywords": "peace, Shanti, goddess, salutations, all beings"},
        {"verse_id": "dm-4-11", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 4, "chapter_name": "Shakra Stuti", "verse_number": 11,
         "text": "yaa devii sarvabhuuteshu maatru ruupena samsthitaa namastasyai namastasyai namastasyai namo namah",
         "translation": "To that Goddess who abides in all beings in the form of the Mother (Maatru) — salutations to Her, salutations to Her, salutations to Her, again and again.",
         "keywords": "mother, Maatru, goddess, salutations, all beings, divine mother"},
        {"verse_id": "dm-11-4", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 11, "chapter_name": "Narayani Stuti", "verse_number": 4,
         "text": "visvesvari tvam paripasi vishvam vishvatmika dharayasiti vishvam vishveshavandya bhavati bhavanti vishvashraya ye tvayi bhakti namrah",
         "translation": "O Ruler of the universe, You protect the universe. You are the soul of the universe, You bear the universe. You are worshipped by the lords of the universe. Those who are devoted to You become the refuge of the universe.",
         "keywords": "universe, ruler, soul, protect, worshipped, devotion, refuge"},
    ]


def get_all_expansion_verses():
    v = []
    v.extend(get_expanded_gita_verses())
    v.extend(get_expanded_upanishad_verses())
    v.extend(get_expanded_veda_verses())
    v.extend(get_expanded_yoga_verses())
    v.extend(get_expanded_mahabharata_verses())
    v.extend(get_expanded_devi_verses())
    return v
