"""
Comprehensive scripture data for Hindu texts:
- Bhagavad Gita (18 chapters)
- Ramayana (7 Kandas)
- Devi Mahatmyam (13 chapters)
"""

def get_scripture_metadata():
    from scripture_data_extended import get_extended_metadata
    from scripture_data_kerala import get_kerala_metadata
    base = [
        {
            "text_id": "bhagavad-gita",
            "name": "Bhagavad Gita",
            "description": "The Song of God - A 700-verse Hindu scripture that is part of the epic Mahabharata. It is a dialogue between Prince Arjuna and Lord Krishna on the battlefield of Kurukshetra.",
            "total_chapters": 18,
            "language": "Sanskrit",
            "image": "https://images.unsplash.com/photo-1643300788512-64b38ad876c6?w=400"
        },
        {
            "text_id": "ramayana",
            "name": "Ramayana",
            "description": "One of the two major Sanskrit epics of ancient India, narrating the life of Rama, prince of Ayodhya. Written by sage Valmiki, it consists of 24,000 verses in seven Kandas.",
            "total_chapters": 7,
            "language": "Sanskrit",
            "image": "https://images.unsplash.com/photo-1617904472808-7e038208077a?w=400"
        },
        {
            "text_id": "devi-mahatmyam",
            "name": "Devi Mahatmyam",
            "description": "The Glory of the Goddess - A Hindu religious text describing the victory of the goddess Durga over the demon Mahishasura. Part of the Markandeya Purana with 700 verses in 13 chapters.",
            "total_chapters": 13,
            "language": "Sanskrit",
            "image": "https://images.unsplash.com/photo-1488875482628-eee706cbfad5?w=400"
        }
    ]
    return base + get_extended_metadata() + get_kerala_metadata()


def get_all_verses():
    from scripture_data_extended import get_extended_verses
    from scripture_data_kerala import get_kerala_verses
    from scripture_data_expansion import get_all_expansion_verses
    from scripture_data_kerala_expansion import get_kerala_expansion_verses
    verses = []
    verses.extend(_gita_verses())
    verses.extend(_ramayana_verses())
    verses.extend(_devi_mahatmyam_verses())
    verses.extend(get_extended_verses())
    verses.extend(get_kerala_verses())
    verses.extend(get_all_expansion_verses())
    verses.extend(get_kerala_expansion_verses())
    return verses


def _gita_verses():
    return [
        # Chapter 1: Arjuna Vishada Yoga (The Yoga of Arjuna's Dejection)
        {"verse_id": "bg-1-1", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 1, "chapter_name": "Arjuna Vishada Yoga", "verse_number": 1, "text": "dhritarashtra uvaca dharma-kshetre kuru-kshetre samaveta yuyutsavah mamakah pandavascaiva kim akurvata sanjaya", "translation": "Dhritarashtra said: O Sanjaya, gathered on the holy field of Kurukshetra, desiring to fight, what did my sons and the sons of Pandu do?", "keywords": "Kurukshetra, battle, Dhritarashtra, Sanjaya"},
        {"verse_id": "bg-1-47", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 1, "chapter_name": "Arjuna Vishada Yoga", "verse_number": 47, "text": "evam uktvarjunah sankhye rathopastha upavisat visrjya sa-saram capam soka-samvigna-manasah", "translation": "Having spoken thus on the battlefield, Arjuna cast aside his bow and arrows, and sat down on the chariot, his mind overwhelmed with grief.", "keywords": "grief, dejection, Arjuna, bow, battlefield"},

        # Chapter 2: Sankhya Yoga (The Yoga of Knowledge)
        {"verse_id": "bg-2-7", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 7, "text": "karpanya-dosopahata-svabhavah prcchami tvam dharma-sammudha-cetah yac chreyah syan niscitam bruhi tan me sisyas te 'ham sadhi mam tvam prapannam", "translation": "My heart is overpowered by the taint of pity, my mind is confused about duty. I ask You to tell me what is best for me. I am Your disciple. Instruct me, who has taken refuge in You.", "keywords": "duty, confusion, disciple, refuge, guidance"},
        {"verse_id": "bg-2-11", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 11, "text": "sri-bhagavan uvaca asocyan anvasocas tvam prajna-vadams ca bhasase gatasun agatasums ca nanusocanti panditah", "translation": "The Supreme Lord said: While speaking learned words, you are mourning for what is not worthy of grief. Those who are wise lament neither for the living nor for the dead.", "keywords": "wisdom, grief, soul, death, knowledge"},
        {"verse_id": "bg-2-13", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 13, "text": "dehino 'smin yatha dehe kaumaram yauvanam jara tatha dehantara-praptir dhiras tatra na muhyati", "translation": "As the embodied soul continuously passes from childhood to youth to old age, the soul similarly passes into another body at death. A self-realized soul is not bewildered by such a change.", "keywords": "soul, reincarnation, body, death, self-realization"},
        {"verse_id": "bg-2-14", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 14, "text": "matra-sparsas tu kaunteya sitosna-sukha-duhkha-dah agamapayino 'nityas tams titiksasva bharata", "translation": "O son of Kunti, the contact between the senses and their objects gives rise to cold, heat, pleasure, and pain. They are transient, arising and disappearing. Bear them patiently, O descendant of Bharata.", "keywords": "senses, pleasure, pain, patience, transient"},
        {"verse_id": "bg-2-17", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 17, "text": "avinasi tu tad viddhi yena sarvam idam tatam vinasam avyayasyasya na kascit kartum arhati", "translation": "That which pervades the entire body you should know to be indestructible. No one can destroy the imperishable soul.", "keywords": "soul, indestructible, imperishable, eternal"},
        {"verse_id": "bg-2-20", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 20, "text": "na jayate mriyate va kadacin nayam bhutva bhavita va na bhuyah ajo nityah sasvato 'yam purano na hanyate hanyamane sarire", "translation": "The soul is never born, nor does it die. It has not come into being, does not come into being, and will not come into being. It is unborn, eternal, ever-existing, and primeval. It is not slain when the body is slain.", "keywords": "soul, eternal, unborn, immortal, death"},
        {"verse_id": "bg-2-22", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 22, "text": "vasamsi jirnani yatha vihaya navani grhnati naro 'parani tatha sarirani vihaya jirnany anyani samyati navani dehi", "translation": "As a person puts on new garments, giving up old ones, the soul similarly accepts new material bodies, giving up the old and useless ones.", "keywords": "body, soul, garments, reincarnation, change"},
        {"verse_id": "bg-2-47", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 47, "text": "karmany evadhikaras te ma phalesu kadacana ma karma-phala-hetur bhur ma te sango 'stv akarmani", "translation": "You have a right to perform your prescribed duty, but you are not entitled to the fruits of action. Never consider yourself the cause of the results of your activities, and never be attached to not doing your duty.", "keywords": "duty, karma, action, fruits, detachment, nishkama karma"},
        {"verse_id": "bg-2-48", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 48, "text": "yoga-sthah kuru karmani sangam tyaktva dhananjaya siddhy-asiddhyoh samo bhutva samatvam yoga ucyate", "translation": "Perform your duty equipoised, O Arjuna, abandoning all attachment to success or failure. Such equanimity is called yoga.", "keywords": "yoga, equanimity, duty, detachment, balance"},
        {"verse_id": "bg-2-62", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 62, "text": "dhyayato visayan pumsah sangas tesupajayate sangat sanjayate kamah kamat krodho 'bhijayate", "translation": "While contemplating the objects of the senses, a person develops attachment for them, and from such attachment lust develops, and from lust anger arises.", "keywords": "desire, attachment, anger, senses, lust, contemplation"},
        {"verse_id": "bg-2-63", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 2, "chapter_name": "Sankhya Yoga", "verse_number": 63, "text": "krodhad bhavati sammohah sammohat smrti-vibhramah smrti-bhramsad buddhi-naso buddhi-nasat pranasyati", "translation": "From anger comes delusion, from delusion bewilderment of memory. When memory is bewildered, intelligence is lost, and when intelligence is lost one falls down again into the material pool.", "keywords": "anger, delusion, memory, intelligence, downfall"},

        # Chapter 3: Karma Yoga
        {"verse_id": "bg-3-9", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 3, "chapter_name": "Karma Yoga", "verse_number": 9, "text": "yajnarthat karmano 'nyatra loko 'yam karma-bandhanah tad-artham karma kaunteya mukta-sangah samacara", "translation": "Work done as a sacrifice for Vishnu has to be performed; otherwise work causes bondage in this material world. Therefore, O son of Kunti, perform your prescribed duties for His satisfaction, and in that way you will always remain free from bondage.", "keywords": "sacrifice, duty, bondage, freedom, karma yoga"},
        {"verse_id": "bg-3-19", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 3, "chapter_name": "Karma Yoga", "verse_number": 19, "text": "tasmad asaktah satatam karyam karma samacara asakto hy acaran karma param apnoti purusah", "translation": "Therefore, without being attached to the fruits of activities, one should act as a matter of duty, for by working without attachment one attains the Supreme.", "keywords": "detachment, duty, action, Supreme, liberation"},
        {"verse_id": "bg-3-21", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 3, "chapter_name": "Karma Yoga", "verse_number": 21, "text": "yad yad acarati sresthas tat tad evetaro janah sa yat pramanam kurute lokas tad anuvartate", "translation": "Whatever action a great man performs, common men follow. And whatever standards he sets by exemplary acts, all the world pursues.", "keywords": "leadership, example, standards, influence, great man"},
        {"verse_id": "bg-3-27", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 3, "chapter_name": "Karma Yoga", "verse_number": 27, "text": "prakrteh kriyamanani gunaih karmani sarvasah ahankara-vimudhatma kartaham iti manyate", "translation": "The spirit soul bewildered by the influence of false ego thinks himself the doer of activities that are in actuality carried out by the three modes of material nature.", "keywords": "ego, false ego, nature, modes, doership, prakruti"},

        # Chapter 4: Jnana Karma Sanyasa Yoga
        {"verse_id": "bg-4-7", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 4, "chapter_name": "Jnana Karma Sanyasa Yoga", "verse_number": 7, "text": "yada yada hi dharmasya glanir bhavati bharata abhyutthanam adharmasya tadatmanam srjamy aham", "translation": "Whenever and wherever there is a decline in righteousness and a predominant rise of unrighteousness, at that time I manifest Myself.", "keywords": "dharma, righteousness, avatar, incarnation, divine manifestation"},
        {"verse_id": "bg-4-8", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 4, "chapter_name": "Jnana Karma Sanyasa Yoga", "verse_number": 8, "text": "paritranaya sadhunam vinasaya ca duskrtam dharma-samsthapanarthaya sambhavami yuge yuge", "translation": "To deliver the pious and to annihilate the miscreants, as well as to reestablish the principles of religion, I advent Myself millennium after millennium.", "keywords": "protection, pious, evil, dharma, avatar, yuga"},
        {"verse_id": "bg-4-33", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 4, "chapter_name": "Jnana Karma Sanyasa Yoga", "verse_number": 33, "text": "sreyan dravya-mayad yajnaj jnana-yajnah parantapa sarvam karmakhilam partha jnane parisamapyate", "translation": "O chastiser of the enemy, the sacrifice performed in knowledge is better than the mere sacrifice of material possessions. After all, O son of Pritha, all sacrifices of work culminate in transcendental knowledge.", "keywords": "knowledge, sacrifice, wisdom, transcendence"},

        # Chapter 5: Karma Sanyasa Yoga
        {"verse_id": "bg-5-10", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 5, "chapter_name": "Karma Sanyasa Yoga", "verse_number": 10, "text": "brahmany adhaya karmani sangam tyaktva karoti yah lipyate na sa papena padma-patram ivambhasa", "translation": "One who performs his duty without attachment, surrendering the results to the Supreme God, is unaffected by sinful action, as the lotus leaf is untouched by water.", "keywords": "lotus, detachment, sin, purity, surrender, duty"},
        {"verse_id": "bg-5-18", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 5, "chapter_name": "Karma Sanyasa Yoga", "verse_number": 18, "text": "vidya-vinaya-sampanne brahmane gavi hastini suni caiva sva-pake ca panditah sama-darsinah", "translation": "The humble sages, by virtue of true knowledge, see with equal vision a learned and gentle brahmana, a cow, an elephant, a dog and a dog-eater.", "keywords": "equality, vision, wisdom, humility, brahman"},

        # Chapter 6: Dhyana Yoga
        {"verse_id": "bg-6-5", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 6, "chapter_name": "Dhyana Yoga", "verse_number": 5, "text": "uddhared atmanatmanam natmanam avasadayet atmaiva hy atmano bandhur atmaiva ripur atmanah", "translation": "One must elevate, not degrade, oneself by one's own mind. The mind is the friend of the conditioned soul, and his enemy as well.", "keywords": "self, mind, friend, enemy, elevation, meditation"},
        {"verse_id": "bg-6-6", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 6, "chapter_name": "Dhyana Yoga", "verse_number": 6, "text": "bandhur atmatmanas tasya yenatmaivatmana jitah anatmanas tu satrutve vartetatmaiva satru-vat", "translation": "For him who has conquered the mind, the mind is the best of friends; but for one who has failed to do so, his very mind will be the greatest enemy.", "keywords": "mind, control, friend, enemy, conquest, self-mastery"},
        {"verse_id": "bg-6-34", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 6, "chapter_name": "Dhyana Yoga", "verse_number": 34, "text": "cancalam hi manah krsna pramathi balavad drdham tasyaham nigraham manye vayor iva su-duskaram", "translation": "The mind is restless, turbulent, obstinate and very strong, O Krishna, and to subdue it, I think, is more difficult than controlling the wind.", "keywords": "mind, restless, control, difficult, wind, meditation"},

        # Chapter 7: Jnana Vijnana Yoga
        {"verse_id": "bg-7-7", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 7, "chapter_name": "Jnana Vijnana Yoga", "verse_number": 7, "text": "mattah parataram nanyat kincid asti dhananjaya mayi sarvam idam protam sutre mani-gana iva", "translation": "O conqueror of wealth, there is no truth superior to Me. Everything rests upon Me, as pearls are strung on a thread.", "keywords": "supreme, truth, divine, pearls, thread, God"},
        {"verse_id": "bg-7-8", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 7, "chapter_name": "Jnana Vijnana Yoga", "verse_number": 8, "text": "raso 'ham apsu kaunteya prabhasmi sasi-suryayoh pranavah sarva-vedesu sabdah khe paurusam nrsu", "translation": "O son of Kunti, I am the taste of water, the light of the sun and the moon, the syllable Om in the Vedic mantras; I am the sound in ether and ability in man.", "keywords": "divine, manifestation, Om, water, sun, moon, Vedas"},

        # Chapter 8: Aksara Brahma Yoga
        {"verse_id": "bg-8-5", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 8, "chapter_name": "Aksara Brahma Yoga", "verse_number": 5, "text": "anta-kale ca mam eva smaran muktva kalevaram yah prayati sa mad-bhavam yati nasty atra samsayah", "translation": "And whoever, at the end of his life, quits his body remembering Me alone at once attains My nature. Of this there is no doubt.", "keywords": "death, remembrance, liberation, God, salvation"},
        {"verse_id": "bg-8-6", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 8, "chapter_name": "Aksara Brahma Yoga", "verse_number": 6, "text": "yam yam vapi smaran bhavam tyajaty ante kalevaram tam tam evaiti kaunteya sada tad-bhava-bhavitah", "translation": "Whatever state of being one remembers when he quits his body, O son of Kunti, that state he will attain without fail.", "keywords": "death, remembrance, consciousness, rebirth, final thought"},

        # Chapter 9: Raja Vidya Raja Guhya Yoga
        {"verse_id": "bg-9-22", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 9, "chapter_name": "Raja Vidya Yoga", "verse_number": 22, "text": "ananyaas cintayanto mam ye janah paryupasate tesam nityabhiyuktanam yoga-ksemam vahamy aham", "translation": "To those who always worship Me with exclusive devotion, meditating on My transcendental form, I carry what they lack and preserve what they have.", "keywords": "devotion, worship, protection, divine care, surrender"},
        {"verse_id": "bg-9-26", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 9, "chapter_name": "Raja Vidya Yoga", "verse_number": 26, "text": "patram pushpam phalam toyam yo me bhaktya prayacchati tad aham bhakty-upahrtam asnami prayatatmanah", "translation": "If one offers Me with love and devotion a leaf, a flower, fruit or water, I will accept it.", "keywords": "devotion, offering, love, simplicity, bhakti"},
        {"verse_id": "bg-9-29", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 9, "chapter_name": "Raja Vidya Yoga", "verse_number": 29, "text": "samo 'ham sarva-bhutesu na me dvesyo 'sti na priyah ye bhajanti tu mam bhaktya mayi te tesu capy aham", "translation": "I envy no one, nor am I partial to anyone. I am equal to all. But whoever renders service unto Me in devotion is a friend, is in Me, and I am also a friend to him.", "keywords": "equality, devotion, friendship, God, impartial"},

        # Chapter 10: Vibhuti Yoga
        {"verse_id": "bg-10-20", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 10, "chapter_name": "Vibhuti Yoga", "verse_number": 20, "text": "aham atma gudakesa sarva-bhutasaya-sthitah aham adis ca madhyam ca bhutanam anta eva ca", "translation": "I am the Self, O Gudakesha, seated in the hearts of all creatures. I am the beginning, the middle and the end of all beings.", "keywords": "self, divine, beginning, end, heart, supreme"},

        # Chapter 11: Vishwarupa Darshana Yoga
        {"verse_id": "bg-11-32", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 11, "chapter_name": "Vishwarupa Darshana Yoga", "verse_number": 32, "text": "kalo 'smi loka-ksaya-krt pravrddho lokan samahartum iha pravrttah rte 'pi tvam na bhavisyanti sarve ye 'vasthitah pratyanikesu yodhah", "translation": "I am Time, the great destroyer of the worlds, and I have come here to destroy all people. With the exception of you, all the soldiers here on both sides will be slain.", "keywords": "time, death, destroyer, cosmic form, Vishwarupa"},
        {"verse_id": "bg-11-33", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 11, "chapter_name": "Vishwarupa Darshana Yoga", "verse_number": 33, "text": "tasmat tvam uttistha yaso labhasva jitva satrun bhunksva rajyam samrddham mayaivaite nihatah purvam eva nimitta-matram bhava savya-sacin", "translation": "Therefore get up and prepare to fight. After conquering your enemies you will enjoy a flourishing kingdom. They are already put to death by My arrangement, and you, O Savyasachi, can be but an instrument in the fight.", "keywords": "instrument, divine will, destiny, fight, victory"},

        # Chapter 12: Bhakti Yoga
        {"verse_id": "bg-12-13", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 12, "chapter_name": "Bhakti Yoga", "verse_number": 13, "text": "advesta sarva-bhutanam maitrah karuna eva ca nirmamo nirahankarah sama-duhkha-sukhah ksami", "translation": "One who is not envious but is a kind friend to all living entities, who does not think himself a proprietor, who is free from false ego, equal in both happiness and distress, and always forgiving.", "keywords": "compassion, kindness, ego-free, forgiveness, equanimity, devotion"},

        # Chapter 13: Kshetra Kshetrajna Vibhaga Yoga
        {"verse_id": "bg-13-28", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 13, "chapter_name": "Kshetra Kshetrajna Vibhaga Yoga", "verse_number": 28, "text": "samam sarvesu bhutesu tisthantam paramesvaram vinasyatsv avinasyantam yah pasyati sa pasyati", "translation": "One who sees the Supersoul equally present everywhere, in every living being, does not degrade himself by his mind. Thus he approaches the transcendental destination.", "keywords": "supersoul, equality, vision, transcendence, divine presence"},

        # Chapter 14: Gunatraya Vibhaga Yoga
        {"verse_id": "bg-14-5", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 14, "chapter_name": "Gunatraya Vibhaga Yoga", "verse_number": 5, "text": "sattvam rajas tama iti gunah prakrti-sambhavah nibadhnanti maha-baho dehe dehinam avyayam", "translation": "Material nature consists of three modes: goodness, passion and ignorance. When the eternal living entity comes in contact with nature, O mighty-armed Arjuna, he becomes conditioned by these modes.", "keywords": "gunas, sattva, rajas, tamas, nature, modes, conditioning"},

        # Chapter 15: Purushottama Yoga
        {"verse_id": "bg-15-7", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 15, "chapter_name": "Purushottama Yoga", "verse_number": 7, "text": "mamaivamso jiva-loke jiva-bhutah sanatanah manah-sasthanindriyani prakrti-sthani karsati", "translation": "The living entities in this conditioned world are My eternal fragmental parts. Due to conditioned life, they are struggling very hard with the six senses, which include the mind.", "keywords": "soul, fragment, divine, senses, struggle, eternal"},
        {"verse_id": "bg-15-15", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 15, "chapter_name": "Purushottama Yoga", "verse_number": 15, "text": "sarvasya caham hrdi sannivisto mattah smrtir jnanam apohanam ca vedais ca sarvair aham eva vedyo vedanta-krd veda-vid eva caham", "translation": "I am seated in everyone's heart, and from Me come remembrance, knowledge and forgetfulness. By all the Vedas, I am to be known. Indeed, I am the compiler of Vedanta, and I am the knower of the Vedas.", "keywords": "heart, knowledge, remembrance, Vedas, Vedanta, omnipresence"},

        # Chapter 16: Daivasura Sampad Vibhaga Yoga
        {"verse_id": "bg-16-1", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 16, "chapter_name": "Daivasura Sampad Vibhaga Yoga", "verse_number": 1, "text": "sri-bhagavan uvaca abhayam sattva-samsuddhir jnana-yoga-vyavasthitih danam damas ca yajnas ca svadhyayas tapa arjavam", "translation": "The Supreme Lord said: Fearlessness, purification of one's existence, cultivation of spiritual knowledge, charity, self-control, performance of sacrifice, study of the Vedas, austerity and simplicity.", "keywords": "divine qualities, fearlessness, charity, self-control, simplicity"},

        # Chapter 17: Sraddhatraya Vibhaga Yoga
        {"verse_id": "bg-17-20", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 17, "chapter_name": "Sraddhatraya Vibhaga Yoga", "verse_number": 20, "text": "datavyam iti yad danam diyate 'nupakarine dese kale ca patre ca tad danam sattvikam smrtam", "translation": "Charity given out of duty, without expectation of return, at the proper time and place, and to a worthy person is considered to be in the mode of goodness.", "keywords": "charity, duty, goodness, sattva, giving"},

        # Chapter 18: Moksha Sanyasa Yoga
        {"verse_id": "bg-18-20", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 18, "chapter_name": "Moksha Sanyasa Yoga", "verse_number": 20, "text": "sarva-bhutesu yenaikam bhavam avyayam iksate avibhaktam vibhaktesu taj jnanam viddhi sattvikam", "translation": "That knowledge by which one undivided spiritual nature is seen in all living entities, though they are divided into innumerable forms, you should understand to be in the mode of goodness.", "keywords": "knowledge, unity, spiritual, goodness, oneness"},
        {"verse_id": "bg-18-46", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 18, "chapter_name": "Moksha Sanyasa Yoga", "verse_number": 46, "text": "yatah pravrttir bhutanam yena sarvam idam tatam sva-karmana tam abhyarcya siddhim vindati manavah", "translation": "By worship of the Lord, who is the source of all beings and who is all-pervading, a man can attain perfection through performing his own work.", "keywords": "worship, perfection, duty, devotion, work"},
        {"verse_id": "bg-18-65", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 18, "chapter_name": "Moksha Sanyasa Yoga", "verse_number": 65, "text": "man-mana bhava mad-bhakto mad-yaji mam namaskuru mam evaishyasi satyam te pratijane priyo 'si me", "translation": "Always think of Me, become My devotee, worship Me and offer your homage unto Me. Thus you will come to Me without fail. I promise you this because you are My very dear friend.", "keywords": "devotion, worship, promise, friendship, surrender, love"},
        {"verse_id": "bg-18-66", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 18, "chapter_name": "Moksha Sanyasa Yoga", "verse_number": 66, "text": "sarva-dharman parityajya mam ekam saranam vraja aham tvam sarva-papebhyo moksayisyami ma sucah", "translation": "Abandon all varieties of religion and just surrender unto Me. I shall deliver you from all sinful reactions. Do not fear.", "keywords": "surrender, liberation, moksha, fearlessness, divine grace, salvation"},
        {"verse_id": "bg-18-78", "text_id": "bhagavad-gita", "text_name": "Bhagavad Gita", "chapter": 18, "chapter_name": "Moksha Sanyasa Yoga", "verse_number": 78, "text": "yatra yogesvarah krsno yatra partho dhanur-dharah tatra srir vijayo bhutir dhruva nitir matir mama", "translation": "Wherever there is Krishna, the master of all mystics, and wherever there is Arjuna, the supreme archer, there will also certainly be opulence, victory, extraordinary power, and morality.", "keywords": "Krishna, Arjuna, victory, opulence, morality, conclusion"},
    ]


def _ramayana_verses():
    return [
        # Bala Kanda (Book of Youth)
        {"verse_id": "ram-1-1", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 1, "chapter_name": "Bala Kanda", "verse_number": 1, "text": "tapah svaadhyaaya niratam tapasvii vaagvidaam varam naradam paripapraccha vaalmiikir muni pungavam", "translation": "The ascetic Valmiki, engaged in penance and study of the Vedas, questioned the great sage Narada, the foremost among the eloquent sages.", "keywords": "Valmiki, Narada, sage, Vedas, beginning"},
        {"verse_id": "ram-1-2", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 1, "chapter_name": "Bala Kanda", "verse_number": 2, "text": "ko nv asmin saampratam loke gunavaan kash ca viiryavaan dharmajna ca krtajna ca satya vaakyo drdha vratah", "translation": "Who in this world today is virtuous, heroic, dutiful, grateful, truthful, and firm in his vows?", "keywords": "virtue, hero, duty, truth, qualities, ideal man"},
        {"verse_id": "ram-1-3", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 1, "chapter_name": "Bala Kanda", "verse_number": 3, "text": "ikshvaaku vamsha prabhavo raamo naama janai shrutah niyataatmaa mahaa viiryah dyutimaan dhrtimaan vashii", "translation": "Born in the Ikshvaku dynasty, known as Rama, he is self-controlled, mighty, radiant, resolute, and master of his senses.", "keywords": "Rama, Ikshvaku, self-control, mighty, radiant"},
        {"verse_id": "ram-1-4", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 1, "chapter_name": "Bala Kanda", "verse_number": 4, "text": "sa ca sarvagunopetah kausalyaa nanda vardhanah samudra iva gaambhiirye dhairyeNa himavaan iva", "translation": "Endowed with all virtues, the joy of Kausalya, he is deep as the ocean in gravity and firm as the Himalayas in courage.", "keywords": "Rama, virtues, ocean, Himalayas, courage, Kausalya"},
        {"verse_id": "ram-1-5", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 1, "chapter_name": "Bala Kanda", "verse_number": 5, "text": "maa nishada pratisthaam tvam agamah shaashvatii samah yat krauncha mithunaat ekam avadhih kaama mohitam", "translation": "O hunter! May you not achieve rest for eternity, for you killed one of a pair of cranes, absorbed in love.", "keywords": "first verse, poetry, compassion, hunter, crane, Valmiki, origin of poetry"},

        # Ayodhya Kanda (Book of Ayodhya)
        {"verse_id": "ram-2-1", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 2, "chapter_name": "Ayodhya Kanda", "verse_number": 1, "text": "pitur vacanam atigamya raamo daasharathih svayam pratasthe vanavaasamya siitaa lakshmanasahitah", "translation": "Honoring his father's word, Rama, the son of Dasharatha, set out for the forest exile, accompanied by Sita and Lakshmana.", "keywords": "exile, forest, duty, father, Rama, Sita, Lakshmana, Dasharatha"},
        {"verse_id": "ram-2-2", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 2, "chapter_name": "Ayodhya Kanda", "verse_number": 2, "text": "raamo vigrahavaan dharmah saadhu satyaparaaKramah raajaa sarvasya lokasya devaanam iva vaasavah", "translation": "Rama is the embodiment of Dharma, noble and of truthful valor. He is the king of the whole world, as Indra is to the gods.", "keywords": "Rama, dharma, embodiment, righteousness, king, truth"},
        {"verse_id": "ram-2-3", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 2, "chapter_name": "Ayodhya Kanda", "verse_number": 3, "text": "na dainya na ca maatsaryam na lobho na shubhaa matih na ca api dainya bhavo vaa drsyate raama sevine", "translation": "Neither sorrow, nor jealousy, nor greed, nor impure thought, nor any meanness is found in one who serves Rama.", "keywords": "service, devotion, purity, Rama, jealousy, greed"},
        {"verse_id": "ram-2-4", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 2, "chapter_name": "Ayodhya Kanda", "verse_number": 4, "text": "atma svaartham parityajya yo anyesham hitam icchhati sarvam tasmai prayacchanti na ca taih paryudasyate", "translation": "He who sacrifices self-interest and desires the welfare of others - to him the world gives everything, and he is never forsaken.", "keywords": "selflessness, welfare, sacrifice, giving, compassion"},

        # Aranya Kanda (Book of the Forest)
        {"verse_id": "ram-3-1", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 3, "chapter_name": "Aranya Kanda", "verse_number": 1, "text": "dharmo rakshati rakshitah", "translation": "Dharma protects those who protect dharma.", "keywords": "dharma, protection, righteousness, universal law"},
        {"verse_id": "ram-3-2", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 3, "chapter_name": "Aranya Kanda", "verse_number": 2, "text": "aatmaanam manushah raama paapaat rakshatu satatam vane vaa raaja veShme vaa apsu vaa sharaNe api vaa", "translation": "O Rama, a man should constantly protect himself from sin, whether in the forest, the palace, in water, or in any refuge.", "keywords": "sin, protection, self-discipline, forest, Rama"},
        {"verse_id": "ram-3-3", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 3, "chapter_name": "Aranya Kanda", "verse_number": 3, "text": "siitaa apaharaNam caiva jaataayoh ca vadhah tathaa raavaNasya ca darpaghnam vaanareNa sahaayatah", "translation": "The abduction of Sita, the slaying of Jatayu, and the humbling of Ravana's pride with the help of the Vanaras.", "keywords": "Sita, abduction, Jatayu, Ravana, Vanaras"},

        # Kishkindha Kanda (Book of Kishkindha)
        {"verse_id": "ram-4-1", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 4, "chapter_name": "Kishkindha Kanda", "verse_number": 1, "text": "vaali vinihato raameNa sugriivasya hitam karan sugriivo raama sahitah siitaam maargiShyate puraat", "translation": "Vali was slain by Rama for the benefit of Sugriva. Sugriva, allied with Rama, shall search for Sita.", "keywords": "Vali, Sugriva, alliance, Sita, search, friendship"},
        {"verse_id": "ram-4-2", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 4, "chapter_name": "Kishkindha Kanda", "verse_number": 2, "text": "snigdhena dhiiraa vipulena cakShushaa raamo mayaa paarthiva putra iiksitah shuShyat mukhena parishoshitaa dharah tena iiva samvatshar gaNo ativartate", "translation": "With moist, deep, and wide eyes, Rama, the prince, was gazed upon by me. With a withered face and parched lips, thus passed a year for him.", "keywords": "Rama, separation, grief, Sita, yearning, prince"},

        # Sundara Kanda (Book of Beauty)
        {"verse_id": "ram-5-1", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 5, "chapter_name": "Sundara Kanda", "verse_number": 1, "text": "tato raavaNa niitaayaah siitaayaah shatra karshaNah iyesha padamanveshTum caaraNaa caritam pathi", "translation": "Then, to find the trail of Sita who was carried away by Ravana, the tormentor of foes (Hanuman) wished to follow the path trodden by celestial beings.", "keywords": "Hanuman, Sita, search, Ravana, celestial path, Lanka"},
        {"verse_id": "ram-5-2", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 5, "chapter_name": "Sundara Kanda", "verse_number": 2, "text": "buddhir balamyadhiShThaanaM dharmo vidyaa ca panchami etaani yasya vartante tasya devah sahaayakrt", "translation": "Intelligence, strength, a good foundation, righteousness, and knowledge as the fifth - to whom these five belong, the gods become his helpers.", "keywords": "intelligence, strength, dharma, knowledge, divine help"},
        {"verse_id": "ram-5-3", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 5, "chapter_name": "Sundara Kanda", "verse_number": 3, "text": "na hi praaNaparikShepe mama raameNa samgamah sukhaM caa aham rameta iha paraH ca aapi mama shashvatam", "translation": "If I give up my life, I shall never meet Rama again. Let me endure here, for my patience is eternal.", "keywords": "Sita, endurance, patience, hope, Rama, Lanka"},
        {"verse_id": "ram-5-4", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 5, "chapter_name": "Sundara Kanda", "verse_number": 4, "text": "nahi me jeevitena artho na arthairna ca sukhena vaa raamamarthaH anaagatya yaa jeevami vipulaamshucham", "translation": "I have no use for life, wealth, or happiness while Rama has not come. That I live bearing such immense sorrow is itself a wonder.", "keywords": "Sita, sorrow, love, devotion, Rama, Lanka, longing"},

        # Yuddha Kanda (Book of War)
        {"verse_id": "ram-6-1", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 6, "chapter_name": "Yuddha Kanda", "verse_number": 1, "text": "nahi praapnoti dharmaaatmaa saadhu vinasha maashritah apradushTa svabhaavo hi na dushTim gaantumarhati", "translation": "A righteous soul devoted to good can never be destroyed. One whose nature is pure cannot be tainted.", "keywords": "righteousness, purity, soul, protection, dharma"},
        {"verse_id": "ram-6-2", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 6, "chapter_name": "Yuddha Kanda", "verse_number": 2, "text": "api svarNamayii lankaa na me lakShmaNa rochate jananii janma bhuumish ca svargaadapi gariyasii", "translation": "Even this golden Lanka does not appeal to me, O Lakshmana. One's mother and motherland are greater than heaven itself.", "keywords": "motherland, patriotism, Lanka, gold, heaven, Rama, Lakshmana"},
        {"verse_id": "ram-6-3", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 6, "chapter_name": "Yuddha Kanda", "verse_number": 3, "text": "vijayeta suparvaano devendra sama vikramah raavaNo naama durvritto rakshasaam iishvarah prabhuh", "translation": "Let Ravana, the wicked lord of Rakshasas, whose valor equals that of Indra himself, be conquered by the noble ones.", "keywords": "Ravana, conquest, battle, valor, Indra, Lanka"},
        {"verse_id": "ram-6-4", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 6, "chapter_name": "Yuddha Kanda", "verse_number": 4, "text": "aaditya hrdayam puNyam sarva shatru vinaashanam jayaavaham japennityam akshayyam paramam shivam", "translation": "This sacred Aditya Hridayam hymn destroys all enemies, bestows victory, and brings eternal blessing and supreme auspiciousness.", "keywords": "Aditya Hridaya, sun, prayer, victory, blessing, enemies"},

        # Uttara Kanda (Book of the Aftermath)
        {"verse_id": "ram-7-1", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 7, "chapter_name": "Uttara Kanda", "verse_number": 1, "text": "raamo raajamaNih sadaa vijayate raamam ramesham bhaje raameNaabhi hataa nishaacharachamuu raamaaya tasmai namah", "translation": "Rama, the jewel among kings, always triumphs. I worship Rama, the Lord of Lakshmi. The demon army was destroyed by Rama. Salutations to that Rama.", "keywords": "Rama, victory, worship, king, salutations, triumph"},
        {"verse_id": "ram-7-2", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 7, "chapter_name": "Uttara Kanda", "verse_number": 2, "text": "raamaaya raamabhadraaya raamacandraaya vedhase raghunaathaaya naathaaya siitaayaah pataye namah", "translation": "Salutations to Rama, to the auspicious Rama, to Ramachandra the creator, to the Lord of the Raghus, to the protector, and to the husband of Sita.", "keywords": "Rama, salutation, Sita, prayer, Raghu dynasty, blessings"},
        {"verse_id": "ram-7-3", "text_id": "ramayana", "text_name": "Ramayana", "chapter": 7, "chapter_name": "Uttara Kanda", "verse_number": 3, "text": "yah patheta raama charitam sarva paapaiH pramucyate", "translation": "Whoever reads the story of Rama is freed from all sins.", "keywords": "reading, Ramayana, sin, liberation, merit, devotion"},
    ]


def _devi_mahatmyam_verses():
    return [
        # Chapter 1: Madhu Kaitabha Vadha (Slaying of Madhu and Kaitabha)
        {"verse_id": "dm-1-1", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 1, "chapter_name": "Madhu Kaitabha Vadha", "verse_number": 1, "text": "savarnih suurya tanayo yo manuh kathyate aShTamah nishaamaya tad utpattim vistaraad gadato mama", "translation": "Savarni, the son of Surya, who is said to be the eighth Manu - hear from me in detail the account of his origin.", "keywords": "Savarni, Manu, Surya, origin, introduction"},
        {"verse_id": "dm-1-2", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 1, "chapter_name": "Madhu Kaitabha Vadha", "verse_number": 2, "text": "jnaaninam api cetaamsi devii bhagavatii hi saa balaadaakrshya mohaaya mahaamayaa prayacchati", "translation": "The great Goddess Mahamaya forcibly draws the minds of even the wise and leads them to delusion.", "keywords": "Mahamaya, delusion, goddess, wisdom, mind, illusion"},
        {"verse_id": "dm-1-3", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 1, "chapter_name": "Madhu Kaitabha Vadha", "verse_number": 3, "text": "tayaa visrjyate vishvam jagatetad akhilam hi yaa tathaa saa hitakaamo'pi kruraa devi mahaasuraan nihanti", "translation": "She by whom this entire world is created and pervaded, the benevolent Goddess, destroys the great demons.", "keywords": "creation, destruction, goddess, demons, benevolence, world"},
        {"verse_id": "dm-1-4", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 1, "chapter_name": "Madhu Kaitabha Vadha", "verse_number": 4, "text": "vishvasya sargaadikaare kriyaaShaktiraakhilam jagat visheshena mahaadevi saa devii trividhaa mataa", "translation": "She is the creative power at the origin of the universe, the entire world. The great Goddess is regarded as threefold.", "keywords": "creation, shakti, goddess, threefold, universe, power"},

        # Chapter 2: Mahishasura Sainya Vadha
        {"verse_id": "dm-2-1", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 2, "chapter_name": "Mahishasura Sainya Vadha", "verse_number": 1, "text": "devaasuramabhudyuddham purnam aabda shatam puraa mahishaasure'sura aaNaam devaanaam ca purandare", "translation": "There was a war between the devas and asuras for a full hundred years, with Mahishasura as the leader of the asuras, and Indra as the leader of the devas.", "keywords": "war, devas, asuras, Mahishasura, Indra, battle"},
        {"verse_id": "dm-2-2", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 2, "chapter_name": "Mahishasura Sainya Vadha", "verse_number": 2, "text": "tatah kopam cakaaroccaiH amaraa nihataashrayaah tasya devaaH samavetraah sharaNam prapidam hareh", "translation": "Then the devas, defeated and deprived of their abodes, became enraged and sought refuge with Lord Vishnu.", "keywords": "devas, defeat, refuge, Vishnu, anger, Mahishasura"},
        {"verse_id": "dm-2-3", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 2, "chapter_name": "Mahishasura Sainya Vadha", "verse_number": 3, "text": "tatah samastha devaanam tejaH samarabhavataha ekasthaam tadanuh kaantim bibhratim atulaam striyam", "translation": "Then from the combined radiance of all the gods emerged a woman of unparalleled brilliance, whose light filled all directions.", "keywords": "Durga, radiance, gods, creation, goddess, divine feminine, brilliance"},

        # Chapter 3: Mahishasura Vadha
        {"verse_id": "dm-3-1", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 3, "chapter_name": "Mahishasura Vadha", "verse_number": 1, "text": "tasya sinhanaadam shrutvaa devii kopena chaavritaa taamaahaviitarShaa devii gambhiira aattahaasata", "translation": "Hearing the lion's roar of that demon, the Goddess, filled with wrath and with a deep, thunderous laugh, spoke.", "keywords": "Devi, wrath, lion, laughter, Mahishasura, battle"},
        {"verse_id": "dm-3-2", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 3, "chapter_name": "Mahishasura Vadha", "verse_number": 2, "text": "tishtha tishtha duraatman mayi yudhyasva sthiro bhava devii uvaacha durga mahishaM tadaagham asuraadhipam", "translation": "Stay! Stay! O wicked one, fight me and stand firm! Thus spoke the Goddess Durga to Mahisha, the king of demons.", "keywords": "Durga, Mahisha, battle, command, bravery, goddess warrior"},
        {"verse_id": "dm-3-3", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 3, "chapter_name": "Mahishasura Vadha", "verse_number": 3, "text": "saa kshiptena cha shakreNa paashenaadbadha mahisham tyaktvaa mahishroopam so'pi svaam roopam aasthitah", "translation": "Bound by the noose of the Goddess, Mahisha abandoned his buffalo form and assumed his true form.", "keywords": "Mahisha, buffalo, transformation, bound, goddess, battle"},

        # Chapter 4: Shakra Stuti (Indra's Hymn)
        {"verse_id": "dm-4-1", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 4, "chapter_name": "Shakra Stuti", "verse_number": 1, "text": "shakrah stuvannasya devyaah daivam stotram amaanavat krtvaa praNamya shriidevyaa jagadambikaayai", "translation": "Indra, the king of the gods, praised the Goddess with a divine hymn, bowing to the Mother of the Universe.", "keywords": "Indra, hymn, praise, goddess, mother, universe"},
        {"verse_id": "dm-4-2", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 4, "chapter_name": "Shakra Stuti", "verse_number": 2, "text": "yaa devii sarvabhuuteshu shakti ruupena samsthitaa namastasyai namastasyai namastasyai namo namah", "translation": "To that Goddess who abides in all beings in the form of power (Shakti) - salutations to Her, salutations to Her, salutations to Her, again and again.", "keywords": "Shakti, goddess, power, salutations, all beings, divine feminine"},
        {"verse_id": "dm-4-3", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 4, "chapter_name": "Shakra Stuti", "verse_number": 3, "text": "yaa devii sarvabhuuteshu buddhi ruupena samsthitaa namastasyai namastasyai namastasyai namo namah", "translation": "To that Goddess who abides in all beings in the form of intelligence (Buddhi) - salutations to Her, salutations to Her, salutations to Her, again and again.", "keywords": "Buddhi, intelligence, goddess, salutations, all beings, wisdom"},
        {"verse_id": "dm-4-4", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 4, "chapter_name": "Shakra Stuti", "verse_number": 4, "text": "yaa devii sarvabhuuteshu nidraa ruupena samsthitaa namastasyai namastasyai namastasyai namo namah", "translation": "To that Goddess who abides in all beings in the form of sleep (Nidra) - salutations to Her, salutations to Her, salutations to Her, again and again.", "keywords": "Nidra, sleep, goddess, salutations, all beings, rest"},
        {"verse_id": "dm-4-5", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 4, "chapter_name": "Shakra Stuti", "verse_number": 5, "text": "yaa devii sarvabhuuteshu kshudaa ruupena samsthitaa namastasyai namastasyai namastasyai namo namah", "translation": "To that Goddess who abides in all beings in the form of hunger (Kshudha) - salutations to Her, salutations to Her, salutations to Her, again and again.", "keywords": "hunger, Kshudha, goddess, salutations, all beings"},
        {"verse_id": "dm-4-6", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 4, "chapter_name": "Shakra Stuti", "verse_number": 6, "text": "yaa devii sarvabhuuteshu chaayaa ruupena samsthitaa namastasyai namastasyai namastasyai namo namah", "translation": "To that Goddess who abides in all beings in the form of reflection (Chhaya) - salutations to Her, salutations to Her, salutations to Her, again and again.", "keywords": "Chhaya, reflection, goddess, salutations, all beings"},
        {"verse_id": "dm-4-7", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 4, "chapter_name": "Shakra Stuti", "verse_number": 7, "text": "yaa devii sarvabhuuteshu shraddaa ruupena samsthitaa namastasyai namastasyai namastasyai namo namah", "translation": "To that Goddess who abides in all beings in the form of faith (Shraddha) - salutations to Her, salutations to Her, salutations to Her, again and again.", "keywords": "faith, Shraddha, goddess, salutations, all beings, devotion"},
        {"verse_id": "dm-4-8", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 4, "chapter_name": "Shakra Stuti", "verse_number": 8, "text": "yaa devii sarvabhuuteshu dayaa ruupena samsthitaa namastasyai namastasyai namastasyai namo namah", "translation": "To that Goddess who abides in all beings in the form of compassion (Daya) - salutations to Her, salutations to Her, salutations to Her, again and again.", "keywords": "compassion, Daya, mercy, goddess, salutations, all beings"},

        # Chapter 5: Devi Duta Samvada
        {"verse_id": "dm-5-1", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 5, "chapter_name": "Devi Duta Samvada", "verse_number": 1, "text": "aham saa paramaa shaktiH jagadyoni sanaatnaii anaadiH saa paraa vidyaa yaa saa nityaaparaajitaa", "translation": "I am that supreme power, the eternal source of the universe. I am that primordial, supreme knowledge, eternally unconquered.", "keywords": "supreme power, eternal, universe, knowledge, unconquered, goddess"},
        {"verse_id": "dm-5-2", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 5, "chapter_name": "Devi Duta Samvada", "verse_number": 2, "text": "haanaayen maanayen nityam stuvanti maam suraah loke saa asmi varadaa nityam bhuktimukti pradaayinii", "translation": "The gods in the heavens constantly praise and honor me. I am the eternal bestower of boons, granting both worldly enjoyment and liberation.", "keywords": "gods, praise, boons, enjoyment, liberation, bestower"},

        # Chapter 6-7: Dhumralochana and Chanda-Munda Vadha
        {"verse_id": "dm-6-1", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 6, "chapter_name": "Dhumralochana Vadha", "verse_number": 1, "text": "ityaajnaapya asau daityo dhuum lokam shaasanam tathaa yayau shaShTi sahasraanam asuraanam samanvitah", "translation": "Thus commanded, the demon Dhumralochana set out with sixty thousand asuras.", "keywords": "Dhumralochana, demon, army, battle, asuras"},
        {"verse_id": "dm-7-1", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 7, "chapter_name": "Chanda Munda Vadha", "verse_number": 1, "text": "tataH chaNDo muNDascha maayadbhyaaM ca shaNDai raviritah vaayuddhyameyau taam deviiM Kaalikaayaastvavochataam", "translation": "Then Chanda and Munda, surrounded by a vast army, marched to battle the Goddess. The Goddess Kali addressed them.", "keywords": "Chanda, Munda, Kali, battle, goddess, army"},
        {"verse_id": "dm-7-2", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 7, "chapter_name": "Chanda Munda Vadha", "verse_number": 2, "text": "tataH kaaliih Chaamundaa iti praahaa jagatpatim prahasya deviim chaNDa muNDaav ubhau vadhiit", "translation": "Then Kali, laughing, spoke to the Lord of the Universe: I have slain both Chanda and Munda. Hence she became known as Chamunda.", "keywords": "Kali, Chamunda, Chanda, Munda, slaying, name origin"},

        # Chapter 8-9: Raktabija Vadha
        {"verse_id": "dm-8-1", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 8, "chapter_name": "Raktabija Vadha", "verse_number": 1, "text": "raktabiijam mahaadaityam shuurimitraanvitam raNe saa devii nirdadhaav aashulalitam jaghne ripum", "translation": "In battle, the Goddess quickly attacked the great demon Raktabija and his allies, and playfully destroyed the enemy.", "keywords": "Raktabija, demon, battle, goddess, destruction, playful"},
        {"verse_id": "dm-8-2", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 8, "chapter_name": "Raktabija Vadha", "verse_number": 2, "text": "tasyahatasya bahudha shakti paataistathaa surah raktam papaata yo yo hi sa sa tatra samaabhavat", "translation": "Wherever his blood fell on the ground, from each drop arose another demon of equal power.", "keywords": "Raktabija, blood, multiplication, demon, magic, power"},
        {"verse_id": "dm-9-1", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 9, "chapter_name": "Nishumbha Vadha", "verse_number": 1, "text": "chalannishumbho nishumbhascha balaavikrama kovidau deviiM abhayadaanena ca tuShTuvuh praahasan mudaa", "translation": "Nishumbha and Shumbha, skilled in valor and might, praised the Goddess with joy, knowing she grants fearlessness.", "keywords": "Nishumbha, Shumbha, valor, fearlessness, praise, goddess"},

        # Chapter 10-11: Shumbha Vadha and Narayani Stuti
        {"verse_id": "dm-10-1", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 10, "chapter_name": "Shumbha Vadha", "verse_number": 1, "text": "tatah shumbhaM nisumbhanca hataasesham balam tathaa kruddho devii samaachakre shastram sarva balam tathaa", "translation": "Then the Goddess, furious at the remaining forces of Shumbha and Nishumbha, prepared all her weapons and divine power.", "keywords": "Shumbha, Nishumbha, weapons, goddess, fury, divine power"},
        {"verse_id": "dm-11-1", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 11, "chapter_name": "Narayani Stuti", "verse_number": 1, "text": "devyaa yayaa tatam idam jagad aatma shaktyaa nishSheSha devagaNa shakti samuuha muurtayaa taam ambikaam akhila deva maharShi puujyaam bhaktyaa nataah sma vidadhaatu shubhaani saa nah", "translation": "She, by whose power this entire universe is pervaded, who is the embodiment of all the powers of the host of gods - to that Ambika, worshipped by all gods and great sages, we bow with devotion. May she grant us auspiciousness.", "keywords": "Ambika, universe, power, gods, devotion, auspiciousness, prayer"},
        {"verse_id": "dm-11-2", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 11, "chapter_name": "Narayani Stuti", "verse_number": 2, "text": "sarvamangala maangalye shive sarvaarthaa saadhike sharaNye tryambake gauri naaraayaNi namostute", "translation": "O auspicious of all that is auspicious, O Shiva, O accomplisher of all objectives, O refuge, O three-eyed Gauri, O Narayani, salutations to you.", "keywords": "Narayani, auspicious, Shiva, Gauri, salutations, prayer, refuge"},
        {"verse_id": "dm-11-3", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 11, "chapter_name": "Narayani Stuti", "verse_number": 3, "text": "srshti sthiti vinaashaanam shakti bhuute sanaatani gunaashraye gunamaye naaraayaNi namostute", "translation": "O eternal one, who is the power behind creation, preservation and destruction, who is the substratum of the gunas, O Narayani, salutations to you.", "keywords": "creation, preservation, destruction, eternal, gunas, Narayani, salutations"},

        # Chapter 12: Phala Stuti (Fruits of Recitation)
        {"verse_id": "dm-12-1", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 12, "chapter_name": "Phala Stuti", "verse_number": 1, "text": "devyaa hataa tatraa daityaaH deva stuvannasya sarvaarthaH siddhi sampaadayanti hi", "translation": "The demons having been slain by the Goddess, the gods praised her. Her hymn bestows the accomplishment of all purposes.", "keywords": "praise, accomplishment, demons, gods, hymn, blessings"},
        {"verse_id": "dm-12-2", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 12, "chapter_name": "Phala Stuti", "verse_number": 2, "text": "sarvaabaadhaaprashamanam trailokya akhileshvari evam eva tvayaa kaaryamasmaad vairi vinaashanam", "translation": "O ruler of all the three worlds, you alleviate all afflictions. Thus you must always destroy our enemies.", "keywords": "three worlds, ruler, afflictions, protection, enemies, prayer"},

        # Chapter 13: Vararoha (Blessings)
        {"verse_id": "dm-13-1", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 13, "chapter_name": "Suratha Vaisya Varadana", "verse_number": 1, "text": "ittham yathaa mahaamaayaa bhagavatii mahaadevi saa bruvantii bhavisyaaham punah punah paraayanam", "translation": "Thus the great Goddess Mahamaya, the supreme Devi, spoke: I shall manifest again and again for the protection of the world.", "keywords": "Mahamaya, manifestation, protection, world, promise, goddess"},
        {"verse_id": "dm-13-2", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 13, "chapter_name": "Suratha Vaisya Varadana", "verse_number": 2, "text": "ya etat paramam devyaash charitam paThate sadaa tasya sarvam bhayam naasti na ca aapadah kaascanaa", "translation": "Whoever always reads this supreme story of the Goddess will have no fear and no calamity.", "keywords": "reading, fearlessness, protection, calamity, blessings, merit"},
        {"verse_id": "dm-13-3", "text_id": "devi-mahatmyam", "text_name": "Devi Mahatmyam", "chapter": 13, "chapter_name": "Suratha Vaisya Varadana", "verse_number": 3, "text": "praNataanam prasiidam tvam devi vishva aartihaarinii trailokya vaasinaam iDye lokaanam varadaa bhava", "translation": "O Goddess, be pleased with those who bow to you. O remover of the afflictions of the universe, worshipped by the inhabitants of the three worlds, be the bestower of boons.", "keywords": "bowing, grace, afflictions, three worlds, boons, goddess, conclusion"},
    ]
